unit svgIcons.FluentUIRegular10.icons;

(* Auto Generated by svgViewer.Generator on 9/14/2024 10:02:36 PM *)

interface

function GetIcon(Index:Integer):String;

implementation

uses
  System.SysUtils,
  svgIcons.FluentUIRegular10.source;

function GetIcon(Index:Integer):String;
begin
  case Index of
    0000 : Result := C_FluentUI_Presence_Available_Regular_10;
    0001 : Result := C_FluentUI_Presence_Away_Regular_10;
    0002 : Result := C_FluentUI_Presence_Blocked_Regular_10;
    0003 : Result := C_FluentUI_Presence_DND_Regular_10;
    0004 : Result := C_FluentUI_Presence_Offline_Regular_10;
    0005 : Result := C_FluentUI_Presence_OOF_Regular_10;
    0006 : Result := C_FluentUI_Presence_Tentative_Regular_10;
    0007 : Result := C_FluentUI_Presence_Unknown_Regular_10;
  end;
end;

end.