unit svgIcons.FluentUIFilled10.names;

(* Auto Generated by svgViewer.Generator on 9/14/2024 10:02:31 PM *)

interface

uses
  System.SysUtils;

const
  C_FluentUIFilled10Count = 4;

function GetName(Index:Integer):String;

implementation

function GetName(Index:Integer):String;
begin
  case Index of
    0000 : Result := 'Presence Available';
    0001 : Result := 'Presence Away';
    0002 : Result := 'Presence Busy';
    0003 : Result := 'Presence DND';
  end;
end;

end.