unit svgIcons.BootstrapFilled16;

(* Auto Generated by svgViewer.Generator on 9/20/2024 9:52:06 AM *)

interface

uses
  System.SysUtils,
  vcl.Graphics,
  vcl.GraphUtil,
  svgViewer.Types;

type
  TBootstrapFilled16IconList = class(TInterfacedObject,ISVGIconList)
  private
    fFillColor : TColor;
  protected
    function GetCount : integer;
    function GetName(Index:Integer):string;
    function GetSource(Index:Integer):string;
    function GetFillColor : TColor;
    procedure SetFillColor(Value:TColor);
  public
    property Count : integer read GetCount;
    property Name[index:integer] : string read GetName;
    property Source[index:integer] : string read GetSource;
    property FillColor : TColor read GetFillColor write SetFillColor default clNone;
  end;

implementation

uses
  svgIcons.BootstrapFilled16.names,
  svgIcons.BootstrapFilled16.icons;

const
  c_icon_count = 660;

function TBootstrapFilled16IconList.GetCount : integer;
begin
  result := 660;
end;

function TBootstrapFilled16IconList.GetFillColor : TColor;
begin
  Result := fFillColor;
end;

procedure TBootstrapFilled16IconList.SetFillColor(Value:TColor);
begin
  fFillColor := Value;
end;

function TBootstrapFilled16IconList.GetName(Index:Integer):string;
begin
  if index > c_icon_count then
    raise EArgumentOutOfRangeException.Create('Requested icon index is out of range');
  result := svgIcons.BootstrapFilled16.names.GetName(Index);
end;

function TBootstrapFilled16IconList.GetSource(Index:Integer):string;
var
  svg : string;
  var
    sColor : string;
begin
  if index > c_icon_count then
    raise EArgumentOutOfRangeException.Create('Requested icon index is out of range');
  if fFillcolor = clNone then
    sColor := ''
  else
    sColor := ' fill="'+ColorToWebColorStr(fFillColor)+'"';
  Result := '<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">'+
    StringReplace(svgIcons.BootstrapFilled16.icons.GetIcon(Index),' fill="#212121"',sColor,[rfReplaceAll])+
    '</svg>';
end;

end.