unit svgIcons.FluentUIRegular10.names;

(* Auto Generated by svgViewer.Generator on 9/14/2024 10:02:36 PM *)

interface

uses
  System.SysUtils;

const
  C_FluentUIRegular10Count = 8;

function GetName(Index:Integer):String;

implementation

function GetName(Index:Integer):String;
begin
  case Index of
    0000 : Result := 'Presence Available';
    0001 : Result := 'Presence Away';
    0002 : Result := 'Presence Blocked';
    0003 : Result := 'Presence DND';
    0004 : Result := 'Presence Offline';
    0005 : Result := 'Presence OOF';
    0006 : Result := 'Presence Tentative';
    0007 : Result := 'Presence Unknown';
  end;
end;

end.