unit svgIcons.FluentUIFilled10.icons;

(* Auto Generated by svgViewer.Generator on 9/14/2024 10:02:31 PM *)

interface

function GetIcon(Index:Integer):String;

implementation

uses
  System.SysUtils,
  svgIcons.FluentUIFilled10.source;

function GetIcon(Index:Integer):String;
begin
  case Index of
    0000 : Result := C_FluentUI_Presence_Available_Filled_10;
    0001 : Result := C_FluentUI_Presence_Away_Filled_10;
    0002 : Result := C_FluentUI_Presence_Busy_Filled_10;
    0003 : Result := C_FluentUI_Presence_DND_Filled_10;
  end;
end;

end.