unit svgIcons.TablerFilled24;

(* Auto Generated by svgViewer.Generator on 12/26/2024 12:08:43 PM *)

interface

uses
  System.SysUtils,
  vcl.Graphics,
  vcl.GraphUtil,
  svgViewer.Types;

type
  TTablerFilled24IconList = class(TInterfacedObject,ISVGIconList)
  private
    fFillColor : TColor;
  protected
    function GetCount : integer;
    function GetName(Index:Integer):string;
    function GetSource(Index:Integer):string;
    function GetFillColor : TColor;
    procedure SetFillColor(Value:TColor);
  public
    property Count : integer read GetCount;
    property Name[index:integer] : string read GetName;
    property Source[index:integer] : string read GetSource;
    property FillColor : TColor read GetFillColor write SetFillColor default clNone;
  end;

implementation

uses
  svgIcons.TablerFilled24.names,
  svgIcons.TablerFilled24.icons;

const
  c_icon_count = 875;

function TTablerFilled24IconList.GetCount : integer;
begin
  result := c_icon_count;
end;

function TTablerFilled24IconList.GetFillColor : TColor;
begin
  Result := fFillColor;
end;

procedure TTablerFilled24IconList.SetFillColor(Value:TColor);
begin
  fFillColor := Value;
end;

function TTablerFilled24IconList.GetName(Index:Integer):string;
begin
  if index > c_icon_count then
    raise EArgumentOutOfRangeException.Create('Requested icon index is out of range');
  result := svgIcons.TablerFilled24.names.GetName(Index);
end;

function TTablerFilled24IconList.GetSource(Index:Integer):string;
var
  sColor,sfill : string;
begin
  if index > c_icon_count then
    raise EArgumentOutOfRangeException.Create('Requested icon index is out of range');
  if fFillcolor = clNone then
    begin
      sFill := '';
      sColor := 'currentColor';
    end
  else
    begin
      sColor := ColorToWebColorStr(fFillColor);
      sFill := ' fill="'+ColorToWebColorStr(fFillColor)+'"';
    end;
  Result := '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">'+
    '<g'+sFill+'>'+
    StringReplace(svgIcons.TablerFilled24.icons.GetIcon(Index),'"currentColor"','"'+sColor+'"',[rfReplaceAll,rfIgnoreCase])+'</g>'+
    '</svg>';
end;

end.